### ISSUE TITLE
website monitoring: add specs.ipfs.tech

### ISSUE THREAD

**Issue by BigLep** [protocol/network-measurements#52]
I just realized from looking at https://github.com/protocol/network-measurements/blob/master/reports/2023/calendar-week-21/ipfs/README.md#website-monitoring that we're missing specs.ipfs.tech.  Please add.  This is needed as part of external monitoring of specs.ipfs.tech per https://github.com/ipfs/specs/issues/418

**Comment by dennis-tra** [comment]
This website is now tracked and available online: https://probelab.io/websites/specs.ipfs.tech/
